INSERT INTO BASE_ID_ENTITY (FIRST_NAME, LAST_NAME, DOC_NUMBER, ID_CARD_TYPE) VALUES
('Vasiliy', 'Berezutskiy', '285921', 'PASSPORT');
INSERT INTO BASE_ID_ENTITY (FIRST_NAME, LAST_NAME, DOC_NUMBER, ID_CARD_TYPE) VALUES
('Sergey', 'Rishikov', '246792', 'MILITARY_CARD');
INSERT INTO BASE_ID_ENTITY (FIRST_NAME, LAST_NAME, DOC_NUMBER, ID_CARD_TYPE) VALUES
('Anna', 'Ahmatova', '675260', 'STUDENT_CARD');
INSERT INTO BASE_ID_ENTITY (FIRST_NAME, LAST_NAME, DOC_NUMBER, ID_CARD_TYPE) VALUES
('Evgeniya', 'Zaytceva', '430936', 'PASSPORT');
INSERT INTO BASE_ID_ENTITY (FIRST_NAME, LAST_NAME, DOC_NUMBER, ID_CARD_TYPE) VALUES
('Franchesko', 'Totti', '790384', 'STUDENT_CARD');
-- INSERT INTO country (name) VALUES ('India');
-- INSERT INTO country (name) VALUES ('Brazil');
-- INSERT INTO country (name) VALUES ('USA');
-- INSERT INTO country (name) VALUES ('Italy');
-- INSERT INTO country (name) VALUES ('LOL');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, BIRTHDATE, GENDER) VALUES
('Vasiliy', 'Berezutskiy', '1978-02-18', 'M');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, BIRTHDATE, GENDER) VALUES
('Sergey', 'Rishikov', '1982-06-22', 'M');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, BIRTHDATE, GENDER) VALUES
('Anna', 'Ahmatova', '1889-07-23', 'F');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, BIRTHDATE, GENDER) VALUES
('Evgeniya', 'Zaytceva', '1992-04-05', 'F');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, BIRTHDATE, GENDER) VALUES
('Franchesko', 'Totti', '1978-03-14', 'M');