INSERT INTO BASE_ID_ENTITY (FIRST_NAME, LAST_NAME, DOC_NUMBER, ID_CARD_TYPE) VALUES
('Vasiliy', 'Berezutskiy', '285921', 'PASSPORT');
INSERT INTO BASE_ID_ENTITY (FIRST_NAME, LAST_NAME, DOC_NUMBER, ID_CARD_TYPE) VALUES
('Sergey', 'Rishikov', '246792', 'MILITARY_CARD');
INSERT INTO BASE_ID_ENTITY (FIRST_NAME, LAST_NAME, DOC_NUMBER, ID_CARD_TYPE) VALUES
('Anna', 'Ahmatova', '675260', 'STUDENT_CARD');
INSERT INTO BASE_ID_ENTITY (FIRST_NAME, LAST_NAME, DOC_NUMBER, ID_CARD_TYPE) VALUES
('Evgeniya', 'Zaytceva', '430936', 'PASSPORT');
INSERT INTO BASE_ID_ENTITY (FIRST_NAME, LAST_NAME, DOC_NUMBER, ID_CARD_TYPE) VALUES
('Franchesko', 'Totti', '790384', 'STUDENT_CARD');
INSERT INTO BASE_ID_ENTITY (FIRST_NAME, LAST_NAME, DOC_NUMBER, ID_CARD_TYPE) VALUES
('Egor', 'Titov', '284821', 'MILITARY_CARD');
INSERT INTO BASE_ID_ENTITY (FIRST_NAME, LAST_NAME, DOC_NUMBER, ID_CARD_TYPE) VALUES
('Roman', 'Pavlyuchenko', '212792', 'STUDENT_CARD');
INSERT INTO BASE_ID_ENTITY (FIRST_NAME, LAST_NAME, DOC_NUMBER, ID_CARD_TYPE) VALUES
('Olga', 'Vyatchinova', '483619', 'PASSPORT');
INSERT INTO BASE_ID_ENTITY (FIRST_NAME, LAST_NAME, DOC_NUMBER, ID_CARD_TYPE) VALUES
('Ekaterina', 'Romanova', '493821', 'PASSPORT');
INSERT INTO BASE_ID_ENTITY (FIRST_NAME, LAST_NAME, DOC_NUMBER, ID_CARD_TYPE) VALUES
('Alehandro', 'Delpiero', '389237', 'STUDENT_CARD');
INSERT INTO BASE_ID_ENTITY (FIRST_NAME, LAST_NAME, DOC_NUMBER, ID_CARD_TYPE) VALUES
('Gordan', 'Freeman', '392012', 'STUDENT_CARD');
INSERT INTO BASE_ID_ENTITY (FIRST_NAME, LAST_NAME, DOC_NUMBER, ID_CARD_TYPE) VALUES
('Alex', 'Shapard', '483029', 'PASSPORT');



INSERT INTO STUDY_GROUP (GROUP_NAME, PEOPLE_COUNT, COURSE_NUMBER) VALUES
('k-255', '20', '2');
INSERT INTO STUDY_GROUP (GROUP_NAME, PEOPLE_COUNT, COURSE_NUMBER) VALUES
('f-324', '20', '3');



INSERT INTO PERSON (FIRST_NAME, LAST_NAME, BIRTHDATE, STUDY_GROUP_ID) VALUES
('Vasiliy', 'Berezutskiy', '1978-01-18', 1);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, BIRTHDATE, STUDY_GROUP_ID) VALUES
('Sergey', 'Rishikov', '1982-06-22', 2);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, BIRTHDATE, STUDY_GROUP_ID) VALUES
('Anna', 'Ahmatova', '1889-07-23', 1);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, BIRTHDATE, STUDY_GROUP_ID) VALUES
('Evgeniya', 'Zaytceva', '1992-04-05', 2);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, BIRTHDATE, STUDY_GROUP_ID) VALUES
('Franchesko', 'Totti', '1978-03-14', 1);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, BIRTHDATE, STUDY_GROUP_ID) VALUES
('Vasiliy', 'Lomovoy', '1976-01-11', 1);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, BIRTHDATE, STUDY_GROUP_ID) VALUES
('Sergey', 'Ignashevich', '1985-08-02', 2);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, BIRTHDATE, STUDY_GROUP_ID) VALUES
('Olga', 'Metlinskaya', '1994-02-27', 1);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, BIRTHDATE, STUDY_GROUP_ID) VALUES
('Elena', 'Prekrasnaya', '2021-01-01', 2);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, BIRTHDATE, STUDY_GROUP_ID) VALUES
('Maksimilliano', 'Bonucchi', '1985-03-11', 1);